version: '3.8'

services:
  user_service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: user-service-1
    ports:
      - "5120:8080"
    networks:
      - app_network
    depends_on:
      - seq

  product_service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    image: product-service:latest
    container_name: product-service-1
    ports:
      - "5130:8080"
    networks:
      - app_network
    depends_on:
      - seq

  cart_service:
    build:
      context: ./CartService
      dockerfile: Dockerfile
    image: cart-service:latest
    container_name: cart-service-1
    ports:
      - "5140:8080"
    networks:
      - app_network
    depends_on:
      - user_service
      - product_service
      - seq

  seq:
    image: datalust/seq:latest
    container_name: seq-1
    ports:
      - "5431:5431"
      - "8081:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  seq_data: